tap "homebrew/bundle"
tap "homebrew/services"
tap "jesseduffield/lazygit", trusted: true
tap "nikitabobko/tap", trusted: true
tap "osx-cross/arm", trusted: true
tap "osx-cross/avr", trusted: true
tap "qmk/qmk", trusted: true
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Generate compilation database for clang tooling
brew "bear"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Statistics utility to count lines of code
brew "cloc"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Diff that understands syntax
brew "difftastic"
# View disk space usage and delete unwanted data, fast
brew "dua-cli"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Language server for the Go language
brew "gopls"
# Command-line hex viewer
brew "hexyl"
# Improved top (interactive process viewer)
brew "htop"
# Command-line benchmarking tool
brew "hyperfine"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Simple terminal UI for git commands
brew "lazygit"
# Pager program similar to more
brew "less"
# Next-gen compiler infrastructure
brew "llvm"
# Remote terminal application
brew "mosh"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Statically typed programming language for scientific computations
brew "numbat"
# Shell command parallelization utility
brew "parallel"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Intuitive find & replace CLI
brew "sd"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Opinionated Lua code formatter
brew "stylua"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Execute commands when watched files change
brew "watchexec"
# Internet file retriever
brew "wget"
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Quantum Mechanical Keyboard (QMK) Firmware
brew "qmk/qmk/qmk"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# Application uninstaller
cask "appcleaner"
# Chromium based browser
cask "arc"
# Create and run Linux containers using lightweight virtual machines
cask "container"
# Disk space visualiser
cask "daisydisk"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome@canary"
# Desktop automation application
cask "hammerspoon"
# Free and open-source media player
cask "iina"
# GPU-based terminal emulator
cask "kitty"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Control your tools with a few keystrokes
cask "raycast"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
