#!/usr/bin/env bash

mods=(
  asdf
  fish
  git
  muxi
  nvim
  starship
  stylua
  tmux
  vim
)

# Find encrypted files and decrypt them
# fd -H -e enc . "$DOTFILES" -x dexios decrypt -f -k "$DOTFILES/master.key" "{}" "{.}"

(cd "${0%/*}" && stow --ignore='.+\.enc' --verbose=2 "${mods[@]}")
