# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Custom_Keybindings.md
# Time format uses Time.Format syntax: https://pkg.go.dev/time#Time.Format
gui:
  border: rounded
  enlargedSideViewLocation: top
  expandFocusedSidePanel: true
  filterMode: fuzzy
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: false
  # commandLogSize: 3
  showDivergenceFromBaseBranch: arrowAndNumber
  showFileTree: false
  shortTimeFormat: 15:04
  timeFormat: 2006-01-02
  skipAmendWarning: true
  skipRewordInEditorWarning: true
  statusPanelView: allBranchesLog
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
  theme:
    activeBorderColor:
      - "#a6d189"
      - bold
    inactiveBorderColor:
      - "#737994"
    searchingActiveBorderColor:
      - "#8caaee"
      - bold
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#292c3c"
      - bold
    cherryPickedCommitBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#8caaee"
    defaultFgColor:
      - default
git:
  autoFetch: false
  autoForwardBranches: none
  pagers:
    - externalDiffCommand: difft --color=always
    - pager: "" # default git diff
  parseEmoji: true
notARepository: "quit"
promptToReturnFromSubprocess: false
keybinding:
  universal:
    confirmInEditor: <alt+enter>
    # return: [h, <esc>]
    goInto: <enter>
    prevBlock-alt: <ctrl+k>
    nextBlock-alt: <ctrl+j>
    prevTab: [h, <alt+h>, <ctrl+h>, <backspace>]
    nextTab: [l, <alt+l>, <ctrl+l>]
  commits:
    moveDownCommit: <alt+j>
    moveUpCommit: <alt+k>
    openLogMenu: <ctrl+g>
    renameCommit: R
    renameCommitWithEditor: r
  files:
    commitChanges: C
    commitChangesWithEditor: c
