# https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_commit\
$status\
$line_break\
$jobs\
$python\
$character"""

right_format = """
$cmd_duration\
$username\
$hostname"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_commit]
format = "[$hash$tag]($style) "
style = "green"

[git_status]
format = "[[($conflicted$modified$staged$renamed$deleted$untracked)]($style) ($ahead_behind$stashed)]($style)"
style = "cyan"
modified = "*"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[status]
format = ' [\[$common_meaning$signal_name$maybe_int\]]($style) '
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"

[username]
format = "[$user]($style)"
style_user = "bright-black"

[hostname]
format = "[@$hostname]($style) "
style = "bright-black"
