gui:
  showBottomLine: false
  showCommandLog: false
  showFileTree: false
  showIcons: true
  theme:
    selectedLineBgColor:
      - '#383838'
    # selectedRangeBgColor:
    #   - '#383838'  # Seems like there's a bug
git:
  paging:
    colorArg: always
    # pager: delta --dark --paging=never  # Delta seems to crash
promptToReturnFromSubprocess: false
keybinding:
  universal:
    nextTab: 'ñ'
    prevTab: 'Ñ'
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
