-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user enable --now hypridle.service")
  hl.exec_cmd("systemctl --user enable --now hyprpaper.service")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("GTK_THEME=Adwaita:dark uwsm app -- swayosd-server")
  hl.exec_cmd("uwsm app -- swaync")
  hl.exec_cmd("uwsm app -- udiskie")
  hl.exec_cmd("systemctl enable --now --user vicinae.service")
  hl.exec_cmd("uwsm app -- waybar")
end)
