# https://github.com/mpv-player/mpv/blob/master/etc/input.conf
#
# mpv --input-keylist
# mpv --input-test --force-window --idle
#
# first four line disables trackpad swiping, otherwise mpv detects trackpad
# gestures as commands and creates a mess. this fixes it. clicking still works.
AXIS_UP    ignore
AXIS_DOWN  ignore
AXIS_LEFT  ignore
AXIS_RIGHT ignore

r no-osd cycle-values video-rotate 0 270 180 90
R no-osd cycle-values video-rotate 0 90 180 270

k cycle pause
h no-osd seek -10 exact; script-message-to material_osc material-osc-show
j no-osd seek -5 exact; script-message-to material_osc material-osc-show
l no-osd seek 10 exact; script-message-to material_osc material-osc-show
; no-osd seek 90 absolute-percent; script-message-to material_osc material-osc-show

shift+j no-osd seek -30 exact; script-message-to material_osc material-osc-show
shift+k no-osd seek 30 exact; script-message-to material_osc material-osc-show
shift+h no-osd seek -60 exact; script-message-to material_osc material-osc-show
shift+l no-osd seek 60 exact; script-message-to material_osc material-osc-show

p script-binding select/select-playlist
left playlist-prev weak; script-message-to material_osc material-osc-show
right playlist-next weak; script-message-to material_osc material-osc-show

up no-osd add volume 2
down no-osd add volume -2

tab script-binding select/select-chapter
ctrl+j add chapter -1
ctrl+l add chapter 1

alt+l cycle-values loop "inf" "no"  # toggle infinite looping
n ab-loop

a cycle audio
s cycle sub
b ignore  # Material OSC has no runtime toggle for its mini seek bar
d script-binding stats/display-stats-toggle
m no-osd cycle mute

/      no-osd playlist-shuffle; no-osd set playlist-pos 0
ctrl+x run /usr/bin/gio trash "${path}"; playlist-remove current
