# https://github.com/mpv-player/mpv/blob/master/etc/input.conf
#
# mpv --input-keylist
# mpv --input-test --force-window --idle
#
# first four line disables trackpad swiping, otherwise mpv detects trackpad
# gestures as commands and creates a mess. this fixes it. clicking still works.
AXIS_UP    ignore
AXIS_DOWN  ignore
AXIS_LEFT  ignore
AXIS_RIGHT ignore

r no-osd cycle-values video-rotate 0 270 180  90
R no-osd cycle-values video-rotate 0  90 180 270

k     cycle pause
space script-binding hold_speed/tap-pause-hold-speed

j       no-osd seek  -5 exact
l       no-osd seek  10 exact
shift+j no-osd seek -30 exact
shift+l no-osd seek  60 exact

shift+h no-osd seek  0 absolute-percent
;       no-osd seek 90 absolute-percent
:       no-osd seek 90 absolute-percent

p     script-binding select/select-playlist
h     playlist-prev
enter playlist-next
/     no-osd playlist-shuffle; no-osd set playlist-pos 0

up   add volume  2
down add volume -2

wheel_up   add volume  2
wheel_down add volume -2

tab    script-binding select/select-chapter
ctrl+j add chapter -1
ctrl+l add chapter 1

alt+l cycle-values loop "inf" "no"  # toggle infinite looping
n ab-loop

a script-binding select/select-aid
s script-binding select/select-sid
b script-binding modernz/progress-toggle
d script-binding stats/display-stats-toggle
m cycle mute

ctrl+x run /usr/bin/gio trash "${path}"; playlist-remove current
g-y    script-binding ytdl_quality/select
