# https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf
# https://mpv.io/manual/stable/

autofit-larger=100%x95%                 # resize window in case it's larger than W%xH% of the screen
autofit-smaller=20%x20%
demuxer-max-back-bytes=128MiB
demuxer-max-bytes=512MiB
msg-module                              # prepend module name to log messages
profile=high-quality                    # struggles with certain image types
term-osd-bar                            # display a progress bar on the terminal

###########
# ModernX #
###########
osc=no
osd-bar-w=25
osd-bar-h=0.4
osd-bar-outline-size=0
osd-bar-marker-style=line
border=no
osd-font-size=16
osd-font="mpv-osd-symbols"
osd-outline-size=1

# Nvidia+Wayland
hwdec=nvdec
gpu-api=opengl
gpu-context=wayland
