#!/usr/bin/env bash

result=$(
  tmux list-keys -T goto |
    awk '!/ -T goto h / { printf("[%s]: %s %s\n", $4, $(NF), $8) }' |
    column -t |
    fzf-tmux -p80%,80% --reverse
)

# Exit cleanly if failed
if [[ $? -ne 0 ]]; then
  exit 0
fi

session_name=$(echo "$result" | awk '{ print $2 }')
session_path=$(echo "$result" | awk '{ print $3 }')

# Create session if it doesn't exist
tmux has-session -t "$session_name" || tmux new-session -d -s "$session_name" -c "$session_path"

tmux switch-client -t "$session_name"
