muxi_prefix = "g"
# tmux_prefix = false
uppercase_overrides = true

[bindings]
c = { popup = { title = " config ",   height = "66%" }, command = "muxi config edit -- +ZenMode" }
e = { popup = { title = " sessions ", height = "66%" }, command = "muxi sessions edit -- +ZenMode" }
s = { popup = { title = " muxi ",     height = "66%" }, command = "muxi sessions switch -i" }
