muxi_prefix = "g"
# tmux_prefix = false
uppercase_overrides = true

[bindings]
e = { popup = { title = " sessions ", height = "66%" }, command = "muxi sessions edit" }
c = { popup = { title = " config ",   height = "66%" }, command = "muxi config edit" }
s = { popup = { title = " muxi ",     height = "66%" }, command = "muxi sessions switch -i" }
