general {
  # lock_cmd = pidof hyprlock || uwsm app -- hyprlock
  # before_sleep_cmd = loginctl lock-session
  # inhibit_sleep = 3
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  timeout = 600
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  timeout = 3600
  on-timeout = systemctl suspend
}
