#!/bin/bash

case $1 in
pre)
  declare -a devices=(XHC)

  for device in "${devices[@]}"; do
    if $(grep -qw ^${device}.*enabled /proc/acpi/wakeup); then
      echo ${device} >/proc/acpi/wakeup
    fi
  done
  ;;
esac
