deadzonesize=0
font=FiraCode Nerd Font
sub_margins=no
tooltip_hints=no
window_controls=no
window_top_bar=no

hover_effect_color=#1d96f5
nibble_color=#1d96f5
seek_handle_border_color=#1d96f5
seek_handle_color=#1d96f5
seekbarfg_color=#1d96f5
