#!/usr/bin/env bash

# curl --proto '=https' --tlsv1.2 -LsSf https://raw.githubusercontent.com/iovis/dotfiles/master/scripts/apple | bash
set -euo pipefail

export DOTFILES="$HOME/.dotfiles"

if [ ! -d "$DOTFILES" ]; then
  echo "[$(date '+%Y-%m-%d %H:%M')] Installing Dotfiles"
  git clone https://github.com/iovis/dotfiles "$DOTFILES"
fi

echo "[$(date '+%Y-%m-%d %H:%M')] Installing Libraries"
if ! command -v brew >/dev/null 2>&1; then
  echo "[$(date '+%Y-%m-%d %H:%M')] Installing Homebrew"
  export NONINTERACTIVE=1
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew bundle --file "$DOTFILES/brew/Brewfile"

echo "[$(date '+%Y-%m-%d %H:%M')] Stow"
cd "$DOTFILES" || exit
stow aerospace bat brew fish fzf git hammerspoon lazygit mise muxi nvim obsidian pry starship stylua tldr tmux vim wezterm
cd || exit

echo "[$(date '+%Y-%m-%d %H:%M')] Installing mise"
if ! command -v mise >/dev/null 2>&1; then
  curl https://mise.run | sh
fi

mise install -y

echo "[$(date '+%Y-%m-%d %H:%M')] Installing rust"
if ! command -v cargo >/dev/null 2>&1; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

. "$HOME/.cargo/env"
cargo install cargo-binstall
cargo binstall -y $(cat "$DOTFILES/default/crates")

echo "[$(date '+%Y-%m-%d %H:%M')] macOS Settings"
defaults write -g NSUseSpellCheckerForCompletions -bool false
defaults write -g NSAllowContinuousSpellChecking -bool false
defaults write -g ApplePressAndHoldEnabled -bool false   # Enable key repeat
defaults write -g NSWindowShouldDragOnGesture -bool true # Drag windows from anywhere with ctrl+cmd+click
defaults write -g com.apple.Dock showhidden -bool true   # Translucent hidden apps in Dock

killall Finder
killall Dock

echo "[$(date '+%Y-%m-%d %H:%M')] Installation ended"

shell=$(basename "$SHELL")
if [ "$shell" != "fish" ]; then
  echo "**************"
  echo "$shell detected."
  echo "Run chsh -s $(which fish)"
fi
