#!/usr/bin/env sh

# curl --proto '=https' --tlsv1.2 -LsSf https://raw.githubusercontent.com/iovis/dotfiles/master/scripts/ubuntu.sh | sh

# TODO:
# - Hyprland
# - Gnome settings (dconf?)
# - Wezterm config for Arch

export DOTFILES="$HOME/.dotfiles"
export LOCAL_BIN="$HOME/.local/bin"
export PROJECT_HOME="$HOME/code/"
export PATH="$LOCAL_BIN:$PATH"

echo "[$(date '+%Y-%m-%d %H:%M')] Installing Libraries"
sudo pacman -Syu

sudo pacman -S --needed base-devel dkms gamemode gnome-disk-utility lib32-gamemode lib32-libvdpau lib32-nvidia-utils lib32-nvidia-utils libvdpau linux-headers man-db nvidia nvidia-utils

sudo pacman -S --needed bat bear clang curl dua-cli eza fastfetch fd ffmpeg firefox fish fzf git git-delta github-cli gopls hexyl htop hurl hyperfine imagemagick jq just lazygit less llvm mpv mtr neovim nmap obsidian parallel qmk ripgrep rsync sd shellcheck shfmt starship steam stow stylua tldr tmux ttf-firacode-nerd unzip watchexec wezterm xh xsel yt-dlp zoxide

# For nvidia driver
sudo mkinitcpio -P

if ! command -v yay >/dev/null 2>&1; then
  echo "[$(date '+%Y-%m-%d %H:%M')] Installing yay"

  mkdir "$PROJECT_HOME"
  cd "$PROJECT_HOME"

  git clone https://aur.archlinux.org/yay.git
  cd yay

  makepkg -si

  cd
  rm -rf "$PROJECT_HOME/yay/"
fi

yay -S --needed 1password zen-browser-bin

echo "[$(date '+%Y-%m-%d %H:%M')] Starting services"
sudo systemctl enable --now bluetooth fstrim.timer sshd

echo "[$(date '+%Y-%m-%d %H:%M')] Installing Dotfiles"
git clone https://github.com/iovis/dotfiles "$DOTFILES"

echo "[$(date '+%Y-%m-%d %H:%M')] Stow"
cd "$DOTFILES" || exit
stow fish fzf git lazygit mise muxi nvim starship stylua tmux vim wezterm

echo "[$(date '+%Y-%m-%d %H:%M')] Installing mise"
if ! command -v mise >/dev/null 2>&1; then
  curl https://mise.run | sh
fi

mise install -y

echo "[$(date '+%Y-%m-%d %H:%M')] Installing rust"
if ! command -v cargo >/dev/null 2>&1; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

. "$HOME/.cargo/env"
cargo install cargo-binstall
cargo binstall -y $(cat "$DOTFILES/default/crates")

echo "[$(date '+%Y-%m-%d %H:%M')] Installation ended"
cd - || exit

shell=$(basename "$SHELL")
if [ "$shell" != "fish" ]; then
  echo "**************"
  echo "$shell detected."
  echo "Run chsh -s $(which fish)"
fi
