#!/usr/bin/env sh

# curl --proto '=https' --tlsv1.2 -LsSf https://raw.githubusercontent.com/iovis/dotfiles/master/scripts/arch | sh
export DOTFILES="$HOME/.dotfiles"
export LOCAL_BIN="$HOME/.local/bin"
export PROJECT_HOME="$HOME/code/"
export PATH="$LOCAL_BIN:$PATH"

echo "[$(date '+%Y-%m-%d %H:%M')] Installing Libraries"
sudo pacman -Syu --noconfirm
sudo pacman -S --needed --noconfirm git

if [ ! -d "$DOTFILES" ]; then
  echo "[$(date '+%Y-%m-%d %H:%M')] Installing Dotfiles"
  git clone https://github.com/iovis/dotfiles "$DOTFILES"
fi

sudo pacman -S --needed --noconfirm $(cat $DOTFILES/pacman/Pacfile)

if ! command -v yay >/dev/null 2>&1; then
  echo "[$(date '+%Y-%m-%d %H:%M')] Installing yay"

  mkdir "$PROJECT_HOME"
  cd "$PROJECT_HOME"

  git clone https://aur.archlinux.org/yay.git
  cd yay

  makepkg -si

  cd
  rm -rf "$PROJECT_HOME/yay/"
fi

yay -S --needed --noconfirm $(cat $DOTFILES/pacman/Yayfile)

echo "[$(date '+%Y-%m-%d %H:%M')] Starting services"
sudo systemctl enable --now avahi-daemon bluetooth fstrim.timer sshd

echo "[$(date '+%Y-%m-%d %H:%M')] Stow"
cd "$DOTFILES" || exit
stow fish fzf git hyprland kitty lazygit mise muxi nvim starship stylua swaync tmux vim waybar wezterm wofi

echo "[$(date '+%Y-%m-%d %H:%M')] Installing mise"
if ! command -v mise >/dev/null 2>&1; then
  curl https://mise.run | sh
fi

mise install -y

echo "[$(date '+%Y-%m-%d %H:%M')] Installing rust"
if ! command -v cargo >/dev/null 2>&1; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

. "$HOME/.cargo/env"
cargo install cargo-binstall
cargo binstall -y $(cat "$DOTFILES/default/crates")

echo "[$(date '+%Y-%m-%d %H:%M')] Installation ended"
cd - || exit

shell=$(basename "$SHELL")
if [ "$shell" != "fish" ]; then
  echo "**************"
  echo "$shell detected."
  echo "Run chsh -s $(which fish)"
fi
