[Personal]
from = Full Name <email>
source = imaps://...
outgoing = smtp://...

# Store in GNOME Keyring:
#   secret-tool store --label='aerc Gmail app password' service aerc account EMAIL
#   secret-tool lookup service aerc account EMAIL
source-cred-cmd = secret-tool lookup service aerc account EMAIL
outgoing-cred-cmd = secret-tool lookup service aerc account EMAIL
# Store in macOS Keyring:
#   /usr/bin/security add-generic-password -a EMAIL -s 'aerc-mail' -U -w
#   /usr/bin/security find-generic-password -a EMAIL -s 'aerc-mail' -w
source-cred-cmd = /usr/bin/security find-generic-password -a EMAIL -s 'aerc-mail' -w
outgoing-cred-cmd = /usr/bin/security find-generic-password -a EMAIL -s 'aerc-mail' -w
outgoing-cred-cmd-cache = true

default = INBOX
cache-headers = true
check-mail = 5m
postpone = [Gmail]/Drafts
archive  = [Gmail]/All Mail
