# Store in GNOME Keyring:
#   secret-tool store --label='aerc Gmail app password' service aerc account EMAIL
#   secret-tool lookup service aerc account EMAIL
[Personal]
from = Full Name <email>
source = imaps://...
source-cred-cmd = secret-tool lookup service aerc account EMAIL
outgoing = smtp://...
outgoing-cred-cmd = secret-tool lookup service aerc account EMAIL

default = INBOX
check-mail = 5m
postpone = [Gmail]/Drafts
archive  = [Gmail]/All Mail
