# Original: /usr/share/aerc/aerc.conf

[general]
default-save-path=~/Downloads
default-menu-cmd=fzf --prompt="❯ " --reverse --gutter=" " --info=hidden --highlight-line --wrap

[ui]
auto-mark-read-split-delay=1s
auto-mark-read-split=true
column-flags={{.Flags | join " "}}
column-name={{.Peer | names | join ", "}}
column-subject={{with .ThreadPrefix}}{{.}} {{end}}{{or .Subject .SubjectBase}}
completion-delay=0ms
dirlist-left={{" "}}{{.Folder}}
dirlist-delay=0ms
fuzzy-complete=true
index-columns=name<20%,subject,flags>=,date>=
mouse-enabled=true
msglist-scroll-offset = 4
next-message-on-delete=false
new-message-bell=false
styleset-name=catppuccin-frappe
tab-title-account=󰇮 {{.Account}}{{with .Unread "INBOX"}} ({{.}}){{end}}
threading-enabled=false

keyhint=true
heyhint-delay=200ms
# keyhint-position=bottom-right

spinner-delimiter=,
spinner-interval=100ms
spinner="⠋,⠙,⠹,⠸,⠼,⠴,⠦,⠧,⠇,⠏"

pinned-tab-marker="󰐃"
icon-attachment=󰁦
icon-deleted=×
icon-draft=✎
icon-encrypted=󰌾
icon-flagged=*
icon-forwarded=↪
icon-invalid=󰅖
icon-marked=✓
icon-new=●
icon-old=●
icon-replied=↩
icon-signed-encrypted=󰌾󰄬
icon-signed=󰄬
icon-unencrypted=
icon-unknown=?

# Thread prefix customization:
thread-prefix-tip = ""
thread-prefix-indent = "  "
thread-prefix-folded = "+"
thread-prefix-unfolded = ""

[statusline]
display-mode=text
column-left=
column-center=
column-right={{.PendingKeys}} {{.TrayInfo | replace `sorting` `` | replace `threading` `󰘬` | replace `passthrough` `󰌓` | replace `visual` `󰄸`}} {{.StatusInfo | replace `Connected` `` | replace `Disconnected` `` | replace `filter` `` | replace `search` ``}}{{" "}}

[viewer]
alternatives=text/plain,text/html  # preferred order of rendering
pager=moor --wrap --statusbar=plain --no-statusbar --no-linenumbers --mousemode=scroll

[compose]
empty-subject-warning=true
no-attachment-warning=^[^>]*attach(ed|ment)

[filters]
.headers=colorize
message/delivery-status=colorize
message/rfc822=colorize
text/calendar=calendar
text/html=! cha -T text/html -o display.image-mode=none
text/plain=colorize

[openers]
#
# Openers allow you to specify the command to use for the :open and :open-link
# actions on a per-MIME-type basis. The :open-link URL scheme is used to
# determine the MIME type as follows: x-scheme-handler/<scheme>.
#
# {} is expanded as the temporary filename or URL to be opened with proper
# shell quoting. If it is not encountered in the command, the filename/URL will
# be appended to the end of the command. The command will then be executed with
# `sh -c`.
#
# Like [filters], openers support basic shell globbing. The first opener which
# matches the part's MIME type (or URL scheme handler MIME type) will be used,
# so order them from most to least specific.
#
# Examples:
# x-scheme-handler/irc=hexchat
# x-scheme-handler/http*=printf '%s' {} | wl-copy
# text/html=surf -dfgms
# text/plain=gvim {} +125
# message/rfc822=thunderbird
application/pdf=kitty --class=widget.pdf -e tdf -f -b FFFFFF -w 000000 {}

[hooks]
mail-received=notify-send --app-name=aerc --icon=mail-unread-symbolic --category=email.arrived "${AERC_FROM_NAME:-${AERC_FROM_ADDRESS:-New mail}}" "${AERC_SUBJECT:-(No subject)}"
