#!/usr/bin/env sh

# Examples in: /opt/homebrew/opt/yabai/share/yabai/examples/yabairc

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap
    # window_animation_duration    0.0            \

# Ignored Apps
yabai -m rule --add app="^1Password" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Backblaze$" manage=off
yabai -m rule --add app="^Bartender" manage=off
yabai -m rule --add app="^Bazecor$" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^DaisyDisk$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Logi Options" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Maps$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Opal Composer$" manage=off
yabai -m rule --add app="^Parallels" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Pastebot$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^TablePlus$" manage=off
yabai -m rule --add app="^Things" manage=off
yabai -m rule --add app="^Tower$" manage=off
yabai -m rule --add app="^Webex$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
