#!/usr/bin/env sh

# Examples in: /opt/homebrew/opt/yabai/share/yabai/examples/yabairc

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp  # bsp or float
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# Ignored Apps
yabai -m rule --add app="^1Password" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Backblaze$" manage=off
yabai -m rule --add app="^Bartender" manage=off
yabai -m rule --add app="^Bazecor$" manage=off
yabai -m rule --add app="^DaisyDisk$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Logi Options" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Maps$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Parallels" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Pastebot$" manage=off
yabai -m rule --add app="^Perimeter" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^Spark Desktop$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^TablePlus$" manage=off
yabai -m rule --add app="^Things" manage=off
yabai -m rule --add app="^Tower$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
