return {
  "andrewradev/splitjoin.vim",
  "chrisbra/csv.vim",
  "christoomey/vim-sort-motion",
  "iovis/browsers_castle",
  "iovis/hubcap.vim",
  "iovis/jirafa.vim",
  "iovis/resize.vim",
  "iovis/substitute.vim",
  "iovis/tux.vim",
  "iovis/vimlook",
  "jparise/vim-graphql",
  "mbbill/undotree",
  "moll/vim-bbye",
  "nvim-lua/plenary.nvim",
  "rrethy/nvim-base16",
  "schickling/vim-bufonly",
  "tommcdo/vim-lion",
  "tpope/vim-abolish",
  "tpope/vim-bundler",
  "tpope/vim-characterize",
  "tpope/vim-dadbod",
  "tpope/vim-dispatch",
  "tpope/vim-dotenv",
  "tpope/vim-eunuch",
  "tpope/vim-fugitive",
  "tpope/vim-git",
  "tpope/vim-projectionist",
  "tpope/vim-ragtag",
  "tpope/vim-rails",
  "tpope/vim-rake",
  "tpope/vim-rbenv",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb",
  "tpope/vim-scriptease",
  "tpope/vim-speeddating",
  "vim-test/vim-test",
  "wbthomason/packer.nvim",
  "wellle/targets.vim",
  "nvim-tree/nvim-web-devicons",
  "christoomey/vim-tmux-navigator",

  {
    "kana/vim-textobj-user",
    dependencies = {
      "kana/vim-textobj-entire",
      "kana/vim-textobj-indent",
    },
  },

  {
    "dstein64/vim-startuptime",
    cmd = "StartupTime",
  },

  {
    "numToStr/Comment.nvim",
    config = true,
  },
}
