return {
  "glepnir/lspsaga.nvim",
  config = function()
    -- https://github.com/glepnir/lspsaga.nvim#lspsaga-ui
    -- https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/highlight.lua
    local colors = {
      normal_bg = "none",
      title_bg = "none",
      blue = "#7cafc2",
      cyan = "#86c1b9",
      green = "#a1b56c",
      magenta = "#ba8baf",
      orange = "#a16946",
      purple = "#CBA6F7", -- TODO: change
      red = "#ab4642",
      yellow = "#f7ca88",
    }

    require("lspsaga").setup({
      diagnostic = {
        jump_num_shortcut = false, -- Seems buggy
        keys = {
          exec_action = "<cr>",
        },
      },
      finder_action_keys = {
        auto_refresh = false,
        open = "<cr>",
      },
      lightbulb = {
        enable = true,
        cache_code_action = false,
        enable_in_insert = false,
        sign = false,
      },
      show_outline = {
        jump_key = "<cr>",
      },
      symbol_in_winbar = {
        enable = false,
      },
      ui = {
        border = "rounded",
        code_action = "",
        colors = colors,
      },
    })

    ---- Highlights
    local hi = require("config.utils").hi

    -- NOTE: There's no current way of changing CodeActionBg0..N because
    --       they are autogenerated (and overwritten) on the spot.
    --       Same for 'DiagnosticMsg' and 'DiagnosticMsgIcon'

    hi.SagaBeacon = {} -- Flash when moving between diagnostics

    -- Code Action
    hi.ActionPreviewNormal = { link = "Comment" }
    hi.CodeActionText = {}
    hi.LspSagaLightBulb = { fg = colors.yellow }

    -- Diagnostic
    hi.DiagnosticSource = { link = "Comment" }

    -- Finder
    hi.FinderIcon = { link = "FinderType" }
    hi.FinderSelection = { fg = colors.blue }
    hi.FinderSpinner = { link = "FinderSpinnerTitle" }
    hi.FinderSpinnerTitle = { fg = colors.blue }
    hi.FinderType = { fg = colors.yellow }
    hi.FinderVirtText = { link = "Comment" }

    -- Rename
    hi.RenameNormal = { fg = colors.cyan }
  end,
}
