map kitty_mod+r load_config_file
map kitty_mod+l next_tab
map kitty_mod+h previous_tab
map kitty_mod+k move_tab_forward
map kitty_mod+j move_tab_backward
map kitty_mod+u remote_control set-background-opacity --toggle 1
